version: '3.8'
services:
  admin_server:
    container_name: admin-server
    restart: always
    build: .
    ports:
      - '5001:5001'

networks:
  default:
    external:
      name: backend-network
