name: Build & Deploy

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy admin-server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # Ip address of the server you wish to ssh into
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          key: ${{ secrets.SSH_KEY }} # Private key of the server should be in /home/isaac/.ssh/id_rsa
          script: |
            eval $(ssh-agent -s)
            ssh-add /home/isaac/.ssh/id_rsa_github
            cd admin-server
            git checkout main
            git pull
            echo ${{ secrets.USER_PASSWORD }} | sudo -S docker-compose rm -sv admin_server
            echo ${{ secrets.USER_PASSWORD }} | sudo -S docker-compose up -d --no-deps --build admin_server
            echo 'Successfully Deploy to DigitalOcean'
